name: Test wiki Windows

on: [push, pull_request]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change
env: 
  TEST: "1"
jobs:

  build-windows:

    runs-on: 'windows-latest'
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setting environment
        run: |
          ./Sphinxsetup.bat
      - name: Test build
        run: |
          python3 ./update.py --parallel 4 --verbose --destdir=./web
